---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: webpacktest
  - name: dependency-cache

run:
  path: webpacktest/ci/scripts/run_tests.sh
